logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
    #        type: TRACE
    com:
      ssafy:
        backend:
          domain:
            member:
              controller: info
        global:
          file:
            controller: info
            service: info

  file:
    name: ./demo.log

server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ssafy

OPENVIDU_URL: https://i8b209.p.ssafy.io:8445
OPENVIDU_SECRET: ssafy

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: ssafy

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 524697668949-st4sbncc7brsgpfb2kaqc604cvr0hfrv.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: XVUGCiFeoQqa6Qc9Q24L
            client-secret: cd9Zbm09h9
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/oauth/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  servlet:
    multipart:
      enabled: true
      location: /temp
      file-size-threshold: 1MB
      max-file-size: 40MB
      max-request-size: 20MB
      
file:
  domain: http://localhost:9999/api/
  upload:
    basicPath: /upload_test/images
    userPath: user
    animalPath: animal
    livePath: live

jwt:
  header: Authorization
  secret: d1659096d8c5bd34c2e96fdb235c123afccf23450af0870d95813d820c0dd44661507fe41d5a12c5b796299d260f314d9a5bdca31050fc00a2a4b44c9d31f93c
  validity-second:
    #    # test1
    #    access: 30
    #    refresh: 120
    #    # test2 - no used refresh
    #    access: 3600
    #    refresh: 3600
    # service
    access: 600
    refresh: 172800
